
import './globals.css'
import React from 'react';
import { Inter } from 'next/font/google'
import Provider from '@/components/provider/Provider'
import ThemeFuntional from '@/components/themeFuntional/ThemeFuntional';
import Layout from '@/components/layoutS/Layout';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard Perron',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

    <html lang="en">
        <body className={inter.className}>
          <ThemeFuntional>
            <Layout>
              {children}
            </Layout>
          </ThemeFuntional>
        </body>
    </html>
  )
}

